name: Release please
description: 'A GitHub Action for automating releases using release-please'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true

  target-branch:
    description: 'The branch to target for the release PR (default: main)'
    required: false
    default: main

outputs:
  pr-number:
    description: 'Release PR number'
    value: ${{ steps.set-pr.outputs.pr-number }}
  prs_created:
    description: 'Whether a release PR was created'
    value: ${{ steps.set-pr-created.outputs.prs_created }}

runs:
  using: "composite"
  steps:
    - name: get release-please config
      id: get-config
      run: |
        echo "Environment: ${inputs.target-branch}"
        
        if [[ "${{ inputs.target-branch }}" == "dev" ]]; then
          echo "config-file=dev-release-please-config.json" >> "$GITHUB_OUTPUT"
          echo "manifest-file=dev-release-please-manifest.json" >> "$GITHUB_OUTPUT"
          echo "Environment: ${inputs.target-branch}"
        else
          echo "config-file=release-please-config.json" >> "$GITHUB_OUTPUT"
          echo "manifest-file=.release-please-manifest.json" >> "$GITHUB_OUTPUT"
        fi
      shell: bash
    - name: Release please
      id: release-please
      uses: googleapis/release-please-action@v4
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        target-branch: ${{ inputs.target-branch }}
        config-file: ${{ steps.get-config.outputs.config-file }}
        manifest-file: ${{ steps.get-config.outputs.manifest-file }}
        
    - name: Set PR output
      id: set-pr
      run: |
        if echo '${{ steps.release-please.outputs.pr }}' | jq -e .number >/dev/null 2>&1; then
          PR_NUMBER=$(echo '${{ steps.release-please.outputs.pr }}' | jq -r .number)
        else
          PR_NUMBER=""
        fi
        echo "pr-number=$PR_NUMBER" >> "$GITHUB_OUTPUT"
      shell: bash

    - name: Set PR created output
      id: set-pr-created
      run: echo "prs_created=${{ steps.release-please.outputs.prs_created }}" >> "$GITHUB_OUTPUT"
      shell: bash